### ISSUE TITLE
Problème de Timer à la création d'un monde sur la première phase

### ISSUE THREAD

**Issue by adgranger** [DjLeChuck/foundryvtt-system-the-heist#1]
Par défaut, il est indiqué 10 minutes mais le timer est sur 10 secondes

![image](https://github.com/DjLeChuck/foundryvtt-system-the-heist/assets/131141262/7a460341-aad9-4bdd-b698-fb3d402aad53)

Il réinitialiser la phase pour qu'il passe bien à 10 minutes

**Comment by DjLeChuck** [comment]
Bien vu ! Corrigé dans la 11.1.1, merci !
